# Generated by Django 3.2.8 on 2021-11-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_pic_image_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
