# Generated by Django 3.2.8 on 2021-11-26 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0016_booking_schedule_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('result_description', models.TextField()),
                ('merchant_id', models.CharField(blank=True, max_length=150, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=150, null=True)),
                ('mpesaReceiptNumber', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county_name', models.CharField(max_length=255)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.counties')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=255)),
                ('sub_county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaResquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantRequestid', models.CharField(max_length=255)),
                ('chechoutrequestid', models.CharField(max_length=255)),
                ('responsecode', models.CharField(max_length=10)),
                ('responsedescription', models.TextField()),
                ('customerMessage', models.TextField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.booking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_code', models.CharField(max_length=255)),
                ('response_description', models.TextField()),
                ('merchant_id', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=255)),
                ('result_code', models.CharField(max_length=255)),
                ('result_description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('request_id', models.TextField()),
                ('mpesa_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.mpesaresquest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
