# Generated by Django 3.2.8 on 2021-11-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='county_id',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='sub_county_id',
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
