# Generated by Django 3.2.8 on 2021-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('values', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
