# Generated by Django 3.2.8 on 2021-11-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_busstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_no',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user_id',
        ),
    ]
