# Generated by Django 3.2.8 on 2021-11-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_travelschedule_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='number_of_passangers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
