# Generated by Django 3.2.8 on 2021-11-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_bus_number_of_passangers'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='type',
            field=models.CharField(choices=[('Express', 'Express'), ('Inter-County', 'Inter-County')], default='', max_length=255),
        ),
    ]
