# Generated by Django 3.2.8 on 2021-11-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_travelschedule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelschedule',
            name='departure_time',
        ),
    ]
