# Generated by Django 3.2.8 on 2021-11-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_travelschedule_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
