# Generated by Django 3.2.8 on 2021-11-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_bus_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
