# Generated by Django 3.2.8 on 2021-11-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_booking_seat_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
