# Generated by Django 3.2.8 on 2021-11-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_booking_date_of_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.travelschedule'),
        ),
    ]
