# Generated by Django 3.2.8 on 2021-11-26 09:14

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_booking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.upload_image_path),
        ),
    ]
