# Generated by Django 3.2.8 on 2021-11-26 16:43

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_image_path),
        ),
    ]
